name: ETL
on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ main ]  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.6"
    - name: cache virtualenv
      uses: actions/cache@v3
      id: cache-venv
      with:
        path: ./.venv/
        key: ${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-venv-${{ hashFiles('requirements.txt ')}}
        restore-keys: |
          ${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-venv-
    - name: Install dependencies
      shell: bash
      run: |
        python -m venv ./.venv
        source ./.venv/bin/activate
        python -m pip install --upgrade pip
        python -m pip install -r ./requirements/requirements.txt
      if: steps.cache-venv.outputs.cache-hit != 'true'
    - name: Install repo project
      shell: bash
      run: |
        source ./.venv/bin/activate
        python -m pip install -r ./requirements/requirements.txt
    - name: Run app
      run: |
        python dftotext.py
    - name: Commit and push
      run: |
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push